services:
  app:
    container_name: ${NODE_CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: .
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    command: npx nodemon server.js
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_LOCAL_PORT}"
    networks:
      - default

networks:
  default:
    name: aurora-jewelry-rnd-network
    external: true

volumes:
  app_node_modules:
    driver: local
